### ISSUE TITLE
Set up spring connection with postgre

### ISSUE THREAD

**Issue by ld0532182** [Vootgor/HeroBattle#2]
Добавить в application.yaml настройки для соединения с БД:
```
spring:
  application:
    name: HeroBattle
  datasource:
    url: jdbc:postgresql://localhost:5432/heroBattle
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
```
